language: scala
scala: 2.11.8 # but this setting isn't used when there's an explicit script
jdk: oraclejdk8
dist: trusty
sudo: false
addons:
  postgresql: 9.4
services:
  - docker
  - postgresql
script: ./bin/run-travis.sh
after_success: if [ $QUASAR_CODECOV == "true" ]; then bash <(curl -s https://codecov.io/bash); fi
notifications:
  irc:
    template:
    - "%{result}: %{repository_slug}#%{build_number} (%{branch}@%{commit}: %{author})
      %{build_url}"
  slack:
    secure: KPCXtCAjtlpRQcH7TQtprrf67yIqPVpht9L6/+wbbNd14Tj3x53fiZ3OTabHVx3SL2ZWxbWq+FJGxdIFMyxC/fC0bV9flB7PlRtqHJV1Q7g49odAMAZL7syWr7vFP5bJt+TXuxHvMBihDHFk1Cehy4a1cnrOMReDgqGIFCwQtbI=

branches:
  except:
    - /^v\d+\.\d+\.\d+-.*$/ # don't redundantly build tags

cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt
  - scripts/marklogic/docker

before_cache:
- find "$HOME/.sbt/" -name '*.lock' -print0 | xargs -0 rm
- find "$HOME/.ivy2/" -name 'ivydata-*.properties' -print0 | xargs -0 rm

env:
  matrix:
  - QUASAR_CODECOV=true SBT_TARGET="; project ygg ; coverage ; test ; coverageReport"
  - QUASAR_CODECOV=false SBT_TARGET="; test:compile ; macros/test ; jsonfile/test"

  global:
  - QUASAR_JSONFILE='{"jsonfile":{"connectionUri":"."}}'
