language: scala
scala:
  - 2.11.2
script: "sbt -DisCoverageRun=true coveralls it:test"
notifications:
  irc:
    channels:
      - "chat.freenode.net#slamdata"
    template:
      - "%{result}: %{repository_slug}#%{build_number} (%{branch}@%{commit}: %{author}) %{build_url}"
