language: scala
scala:
  - 2.11.2

script: "sbt ++$TRAVIS_SCALA_VERSION scoverage:test"

notifications:
  irc:
    channels:
      - "chat.freenode.net#slamdata"
    template:
      - "%{result}: %{repository_slug}#%{build_number} (%{branch}@%{commit}: %{author}) %{build_url}"
