language: scala
scala:
  - 2.11.2
script:         "./scripts/jenkins"
after_success:  "./scripts/jenkinsSuccess"
notifications:
  irc:
    channels:
      - "chat.freenode.net#slamdata"
    template:
      - "%{result}: %{repository_slug}#%{build_number} (%{branch}@%{commit}: %{author}) %{build_url}"
env:
  - TRAVIS_BUILD=true