language: scala
scala:
  - 2.11.2
sudo: false
before_install:
  - "./scripts/installMongo"
  - "export PATH=$HOME/mongo:$PATH"
script:         "./scripts/build"
after_success:  "./scripts/buildSuccess"
after_failure:  "./scripts/buildFailure"
notifications:
  irc:
    channels:
      - "chat.freenode.net#slamdata"
    template:
      - "%{result}: %{repository_slug}#%{build_number} (%{branch}@%{commit}: %{author}) %{build_url}"
env: 
  global:
    - LOCAL_MONGODB=true