sudo: false
language: scala
scala: 2.9.3
jdk: oraclejdk7

cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt

before_cache:
- find "$HOME/.sbt/" -name '*.lock' -print0 | xargs -0 rm
- find "$HOME/.ivy2/" -name 'ivydata-*.properties' -print0 | xargs -0 rm
