addons:
  apt:
    packages:
    - moreutils

sudo: false
language: scala
scala: 2.11.8
jdk: oraclejdk8
script: ./bin/run-travis.sh
after_success:
- if [ $QUASAR_CODECOV == "true" ]; then bash <(curl -s https://codecov.io/bash); fi

branches:
  except:
    - /^v\d+\.\d+\.\d+-.*$/ # don't redundantly build tags

cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt

before_cache:
- find "$HOME/.sbt/" -name '*.lock' -print0 | xargs -0 rm
- find "$HOME/.ivy2/" -name 'ivydata-*.properties' -print0 | xargs -0 rm

env:
  matrix:
  - QUASAR_CODECOV=true SBT_TARGET="; project ygg ; coverage ; test ; coverageReport"
  - QUASAR_CODECOV=false SBT_TARGET="; project it ; testOnly $(echo quasar.fs.{Read,Write,Query,Manage}FilesSpec)"

  global:
  - QUASAR_JSONFILE='{"jsonfile":{"connectionUri":"."}}'
