sudo: false
language: scala
scala: 2.11.8
jdk:
  - oraclejdk7
  - oraclejdk8
script: ./bin/tests

cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt

before_cache:
- find "$HOME/.sbt/" -name '*.lock' -print0 | xargs -0 rm
- find "$HOME/.ivy2/" -name 'ivydata-*.properties' -print0 | xargs -0 rm
