addons:
  apt:
    packages:
    - moreutils

sudo: false
language: scala
scala: 2.11.8
jdk: oraclejdk8
script: ./bin/run-travis.sh
after_success:
- if [ $QUASAR_CODECOV == "true" ]; then bash <(curl -s https://codecov.io/bash); fi

cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt

before_cache:
- find "$HOME/.sbt/" -name '*.lock' -print0 | xargs -0 rm
- find "$HOME/.ivy2/" -name 'ivydata-*.properties' -print0 | xargs -0 rm

env:
  matrix:
  - SBT_TARGET="; project ygg ; coverage ; test ; coverageReport"
  - SBT_TARGET="ygg/test"
